### ISSUE TITLE
doesn't build on mac

### ISSUE THREAD

**Issue by mihxil** [npo-poms/functional-tests#105]
See https://github.com/npo-poms/functional-tests/actions/runs/7458898087

**Comment by mihxil** [comment]
@ronnygun Could you look into this?

**Comment by ronnygun** [comment]
@mihxil FitNesse doesn't support Java version 21. Please install Java version 17.

![Java version 21](https://github.com/npo-poms/functional-tests/assets/30461412/0a54d9a4-a316-4979-af9a-95640ed56533)

Our Jenkins uses Java version 17.

![Java version 17](https://github.com/npo-poms/functional-tests/assets/30461412/88a852db-57ad-466a-bf83-06e2c4ce297f)

**Comment by mihxil** [comment]
That doesn't make a difference:

https://github.com/npo-poms/functional-tests/actions/runs/7472855538

**Comment by ronnygun** [comment]
This error only occurs in GitHub Actions (and not in Jenkins) at the plugin 'jetspeed-unpack-maven-plugin' (https://mvnrepository.com/artifact/nl.praegus/jetspeed-unpack-maven-plugin/2.3.2).

It's related to the pom.xml, but I've used the pom.xml in the GitHub account of fhoeben: https://github.com/fhoeben/sample-fitnesse-project/blob/master/pom.xml

**Comment by ronnygun** [comment]
I have fixed it and it works now:

https://github.com/npo-poms/functional-tests/actions/runs/7538109450

![GitHub Actions - alles groen](https://github.com/npo-poms/functional-tests/assets/30461412/d6fb8cf6-489e-4936-87fa-002afc2fb434)

**Comment by mihxil** [comment]
It didn't only occur on github actions. The same thing happened on my machine (a mac), which made it a bit unpleasant to work with.  But thanks, I'll look into into it.
