### ISSUE TITLE
I can't get many tests running. 

### ISSUE THREAD

**Issue by mihxil** [npo-poms/functional-tests#107]
E.g. a CMS selector test. May exception. I can't seem to find what they are. It's just a giant heap of  errors.

![Screenshot 2024-01-23 at 11 40 43](https://github.com/npo-poms/functional-tests/assets/429477/7c6ee185-8f36-47bb-bd53-357d0f274bb2)

The 'execution log' isn't very helpful either. 

It's unclear what it is trying to say to me.

**Comment by mihxil** [comment]
May it goed better with java 11. It seems that even java 17 is not supported?

**Comment by ronnygun** [comment]
Java 17 is installed on my Windows pc and NPO-TA 78 works there.

![2024-01-23 14_38_44-Greenshot](https://github.com/npo-poms/functional-tests/assets/30461412/31591e5c-361f-4c1b-a3e7-54abceba1f84)

**Comment by ronnygun** [comment]
@mihxil I suspect you have Apache Maven 3.9.x on your machine, which is not supported by FitNesse. Please install Apache Maven 3.8.x, available at https://maven.apache.org/download.cgi.

**Comment by mihxil** [comment]
Come on, you can't be serious. I'm not going to have different versions of maven. I'd rather switch java versions, which seems to resolve this too.
